channels:
- conda-forge
dependencies:
- python=3.9.4
- pip<=20.2.3
- pip:
  - mlflow
  - cloudpickle==2.1.0
  - dvc==2.10.2
  - ipywidgets==7.7.0
  - scikit-learn==1.1.1
  - seaborn==0.11.2
name: mlflow-env
