channels:
- conda-forge
dependencies:
- python=3.9.2
- pip<=20.2.3
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - dvc==2.10.2
  - ipywidgets==7.7.0
  - scikit-learn==1.0.2
  - seaborn==0.11.2
  - statsmodels==0.13.2
name: mlflow-env
